create table public.bookings (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  pickup_location text,
  day text not null,
  venue text not null,
  time_slot text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.bookings enable row level security;

-- Create policy to allow public inserts
create policy "Allow anonymous inserts" on public.bookings 
for insert with check (true);
